// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVDW4iz90x8LtQoBmd0zcw8Mh0MiVvfc',
    appId: '1:24220641787:web:d238753042431f891f035e',
    messagingSenderId: '24220641787',
    projectId: 'flutter-http-ece83',
    authDomain: 'flutter-http-ece83.firebaseapp.com',
    databaseURL: 'https://flutter-http-ece83-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-http-ece83.appspot.com',
    measurementId: 'G-83BEPG3T2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDqeoTVU3PcdTV5ApBM-pdToGQaQvAvc',
    appId: '1:24220641787:android:8d6c80b85a37b2101f035e',
    messagingSenderId: '24220641787',
    projectId: 'flutter-http-ece83',
    databaseURL: 'https://flutter-http-ece83-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-http-ece83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3geW228ynnxtA1celdBIenbemllmw0CQ',
    appId: '1:24220641787:ios:25576589bc28d8771f035e',
    messagingSenderId: '24220641787',
    projectId: 'flutter-http-ece83',
    databaseURL: 'https://flutter-http-ece83-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-http-ece83.appspot.com',
    iosClientId: '24220641787-r5mkqf5q6kaddbphal568vfrsm0qik6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

}